/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\prototype3.gltf 
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { gsap } from "gsap";
import	 { useLayoutEffect, useRef } from "react";

export const FLOOR_HEIGHT = 2;
export const NB_FLOORS = 3;

export function Prototype3(props) {
	const { nodes, materials } = useGLTF("./models/prototype3.gltf");
	const ref = useRef();
	const tl = useRef();
	const floorThreeRef = useRef();
	const floorTwoRef = useRef();
	const floorOneRef = useRef();
	const scroll = useScroll();

	useFrame(() => {
		tl.current.seek(scroll.offset * tl.current.duration());
	});

	useLayoutEffect(() => {
		tl.current = gsap.timeline();

		// VERTICAL ANIMATION
		// tl.current.to(
		// 	ref.current.position,
		// 	{
		// 		duration: 2,
		// 		y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
		// 	},
		// 	0
		// );

		
	}, []);

	return (
		<group {...props} dispose={null} ref={ref} position={[-1, -1, 1]}>
			<group position={[-4, 4, -4]}>
				<group ref={floorThreeRef}>
					<mesh
						geometry={nodes.Cube003.geometry}
						material={materials["Material.004"]}
					/>
					<mesh
						geometry={nodes.Cube003_1.geometry}
						material={materials["Material.005"]}
					/>
				</group>
			</group>
			<group position={[-2, 2, -2]}>
				<group ref={floorTwoRef}>
					<mesh
						geometry={nodes.Cube004.geometry}
						material={materials["Material.002"]}
					/>
					<mesh
						geometry={nodes.Cube004_1.geometry}
						material={materials["Material.003"]}
					/>
				</group>
			</group>
			<group position={[0, 0, 0]}>
				<group ref={floorOneRef}>
					<mesh
						geometry={nodes.Cube002.geometry}
						material={materials["Material.001"]}
					/>
					<mesh
						geometry={nodes.Cube002_1.geometry}
						material={materials["Material.000"]}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("./models/prototype3.gltf");
